import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { generateSessionReport, writeSessionReport, type SessionReportContext } from '../lib/session-report.js';

function makeCtx(overrides: Partial<SessionReportContext> = {}): SessionReportContext {
  return {
    repoRoot: '/tmp/test-repo',
    startTime: Date.now() - 3600_000, // 1 hour ago
    cycleCount: 5,
    allPrUrls: [],
    totalPrsCreated: 0,
    totalFailed: 1,
    totalMergedPrs: 0,
    totalClosedPrs: 0,
    totalMilestonePrs: 0,
    milestoneMode: false,
    isContinuous: true,
    shutdownRequested: false,
    maxPrs: 5,
    endTime: null,
    totalMinutes: 60,
    sectorState: null,
    allLearningsCount: 10,
    allTicketOutcomes: [],
    activeFormula: null,
    userScope: undefined,
    parallelExplicit: false,
    parallelOption: undefined,
    completedDirectTickets: [
      { title: 'Fix null check in auth handler', category: 'fix', files: ['src/auth.ts', 'src/auth.test.ts'] },
      { title: 'Add coverage for payment module', category: 'test', files: ['src/payment.test.ts'] },
      { title: 'Refactor utils to reduce duplication', category: 'refactor', files: ['src/utils.ts'] },
    ],
    ...overrides,
  };
}

describe('generateSessionReport', () => {
  it('produces valid markdown with all sections', () => {
    const report = generateSessionReport(makeCtx());

    expect(report).toContain('# PromptWheel Session Report');
    expect(report).toContain('## Results');
    expect(report).toContain('| Cycles | 5 |');
    expect(report).toContain('| Tickets completed | 3 |');
    expect(report).toContain('| Tickets failed | 1 |');
    expect(report).toContain('| Files modified | 4 |');
    expect(report).toContain('## Tickets');
    expect(report).toContain('Fix null check in auth handler');
    expect(report).toContain('Add coverage for payment module');
    expect(report).toContain('## Health');
    expect(report).toContain('Learnings: 10 accumulated');
    expect(report).toContain('Generated by [PromptWheel]');
  });

  it('produces minimal report with zero tickets', () => {
    const report = generateSessionReport(makeCtx({
      completedDirectTickets: [],
      totalFailed: 0,
      cycleCount: 0,
    }));

    expect(report).toContain('# PromptWheel Session Report');
    expect(report).toContain('| Tickets completed | 0 |');
    expect(report).toContain('| Files modified | 0 |');
    // No Tickets section when there are no tickets
    expect(report).not.toContain('## Tickets');
  });

  it('includes PR URLs when present', () => {
    const report = generateSessionReport(makeCtx({
      allPrUrls: ['https://github.com/org/repo/pull/1', 'https://github.com/org/repo/pull/2'],
    }));

    expect(report).toContain('## Pull Requests');
    expect(report).toContain('https://github.com/org/repo/pull/1');
    expect(report).toContain('https://github.com/org/repo/pull/2');
  });

  it('shows formula name when active', () => {
    const report = generateSessionReport(makeCtx({
      activeFormula: { name: 'security-audit', description: 'test', prompt: '' } as any,
    }));

    expect(report).toContain('**Formula:** security-audit');
  });

  it('shows scope when set', () => {
    const report = generateSessionReport(makeCtx({ userScope: 'src/api/**' }));
    expect(report).toContain('**Scope:** src/api/**');
  });
});

describe('writeSessionReport', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'promptwheel-report-test-'));
    const bsDir = path.join(tmpDir, '.promptwheel');
    fs.mkdirSync(bsDir, { recursive: true });
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it('creates file in .promptwheel/reports/', () => {
    const report = '# Test Report\nHello';
    const relPath = writeSessionReport(tmpDir, report);

    expect(relPath).toMatch(/^\.promptwheel\/reports\/session-.*\.md$/);

    const absPath = path.join(tmpDir, relPath);
    expect(fs.existsSync(absPath)).toBe(true);
    expect(fs.readFileSync(absPath, 'utf-8')).toBe(report);
  });

  it('creates reports directory if it does not exist', () => {
    const reportsDir = path.join(tmpDir, '.promptwheel', 'reports');
    expect(fs.existsSync(reportsDir)).toBe(false);

    writeSessionReport(tmpDir, '# Test');

    expect(fs.existsSync(reportsDir)).toBe(true);
  });
});
