/**
 * Scout types - Shared type definitions for codebase scanning
 */

/**
 * Proposal categories
 */
export type ProposalCategory = 'refactor' | 'docs' | 'test' | 'perf' | 'security';

/**
 * Complexity levels
 */
export type ComplexityLevel = 'trivial' | 'simple' | 'moderate' | 'complex';

/**
 * A ticket proposal generated by the scout
 */
export interface TicketProposal {
  /** Unique ID (scout-{timestamp}-{random}) */
  id: string;
  /** Category of improvement */
  category: ProposalCategory;
  /** Short, actionable title */
  title: string;
  /** What needs to be done and why */
  description: string;
  /** Verifiable acceptance criteria */
  acceptance_criteria: string[];
  /** Commands to verify the fix */
  verification_commands: string[];
  /** Files that can be modified */
  allowed_paths: string[];
  /** Specific files identified for change */
  files: string[];
  /** Confidence score (0-100) */
  confidence: number;
  /** Impact score (1-10, optional) — how much this matters */
  impact_score?: number;
  /** Why this improvement matters */
  rationale: string;
  /** Estimated complexity */
  estimated_complexity: ComplexityLevel;
}

/**
 * Scout configuration options
 */
export interface ScoutOptions {
  /** Glob pattern for files to scan (e.g., "src/**") */
  scope: string;
  /** Filter to specific categories */
  types?: ProposalCategory[];
  /** Categories to exclude */
  excludeTypes?: ProposalCategory[];
  /** Glob patterns to exclude */
  exclude?: string[];
  /** Maximum proposals to generate (default: 10) */
  maxProposals?: number;
  /** Minimum confidence threshold (default: 50) */
  minConfidence?: number;
  /** Working directory (default: cwd) */
  projectPath?: string;
  /** Timeout per batch in ms (default: 120000) */
  timeoutMs?: number;
  /** Cancellation signal */
  signal?: AbortSignal;
  /** Progress callback */
  onProgress?: (progress: ScoutProgress) => void;
  /** Recently completed ticket titles to avoid duplicates */
  recentlyCompletedTitles?: string[];
  /** Model to use (default: opus) */
  model?: 'haiku' | 'sonnet' | 'opus';
  /** Custom prompt from formula — tells the AI what to focus on */
  customPrompt?: string;
  /** Scout backend to use (default: ClaudeScoutBackend) */
  backend?: import('./runner.js').ScoutBackend;
  /** Files the scout can read but must NOT propose changes to */
  protectedFiles?: string[];
  /** Token budget per batch (default: auto based on backend) */
  batchTokenBudget?: number;
  /** Maximum files to scan per cycle (default: 60) */
  maxFiles?: number;
}

/**
 * Progress update during scanning
 */
export interface ScoutProgress {
  /** Current phase */
  phase: 'discovering' | 'analyzing' | 'generating' | 'complete';
  /** Files scanned so far */
  filesScanned: number;
  /** Total files to scan */
  totalFiles: number;
  /** Proposals found so far */
  proposalsFound: number;
  /** Current batch number */
  currentBatch: number;
  /** Total batches */
  totalBatches: number;
  /** Current file being processed */
  currentFile?: string;
}

/**
 * Scout result
 */
export interface ScoutResult {
  /** Whether the scan completed successfully */
  success: boolean;
  /** Generated proposals */
  proposals: TicketProposal[];
  /** Any errors encountered */
  errors: string[];
  /** Total files scanned */
  scannedFiles: number;
  /** Total scan duration in ms */
  scanDurationMs: number;
}

/**
 * Schema for validating LLM output
 */
export const PROPOSAL_SCHEMA = {
  type: 'object',
  properties: {
    proposals: {
      type: 'array',
      items: {
        type: 'object',
        required: [
          'category',
          'title',
          'description',
          'acceptance_criteria',
          'verification_commands',
          'allowed_paths',
          'files',
          'confidence',
          'rationale',
          'estimated_complexity',
        ],
        properties: {
          category: { type: 'string', enum: ['refactor', 'docs', 'test', 'perf', 'security'] },
          title: { type: 'string' },
          description: { type: 'string' },
          acceptance_criteria: { type: 'array', items: { type: 'string' } },
          verification_commands: { type: 'array', items: { type: 'string' } },
          allowed_paths: { type: 'array', items: { type: 'string' } },
          files: { type: 'array', items: { type: 'string' } },
          confidence: { type: 'number', minimum: 0, maximum: 100 },
          impact_score: { type: 'number', minimum: 1, maximum: 10 },
          rationale: { type: 'string' },
          estimated_complexity: { type: 'string', enum: ['trivial', 'simple', 'moderate', 'complex'] },
        },
      },
    },
  },
  required: ['proposals'],
} as const;
